INSERT INTO Employee(FirstName, LastName, Department, Position, OfficePhone, EmailAddress) VALUES('Mary', 'Jacobs', 'Administration', 'CEO', '360-285-8110', 'Mary.Jacobs@WP.com');
INSERT INTO Employee VALUES('Rosalie', 'Jackson', 'Administration','Admin Assistant', 1, '360-285-8120', 'Rosalie.Jackson@WP.com');
INSERT INTO Employee VALUES('Richard', 'Bandalone', 'Legal', 'Attorney', 1, '360-285-8210', 'Richard.Bandalone@WP.com');
INSERT INTO Employee VALUES('George', 'Smith', 'Human Resources', 'HR3', 1, '360-285-8310', 'George.Smith@WP.com');
INSERT INTO Employee VALUES('Alan', 'Adams', 'Human Resources', 'HR1', 4, '360-285-8320', 'Alan.Adams@WP.com');
INSERT INTO Employee VALUES('Ken', 'Evans', 'Finance', 'CFO', 1, '360-285-8410', 'Ken.Evans@WP.com');
INSERT INTO Employee VALUES('Mary', 'Abernathy', 'Finance', 'FA3', 6, '360-285-8420', 'Mary.Abernathy@WP');
INSERT INTO Employee VALUES('Tom', 'Caruthers', 'Accounting', 'FA2', 6, '360-285-8430', 'Tom.Caruthers@WP.com');
INSERT INTO Employee VALUES('Heather', 'Jones', 'Accounting', 'FA2', 6, '360-285-8440', 'Heather.Jones@WP.com');
INSERT INTO Employee VALUES('Ken', 'Numoto', 'Sales and Marketing', 'SM3', 1, '360-287-8510', 'Ken.Numoto@WP.com');
INSERT INTO Employee VALUES('Linda', 'Granger', 'Sales and Marketing', 'SM2', 10, '360-287-8520', 'Linda.Granger@WP.com');
INSERT INTO Employee VALUES('James', 'Nestor', 'InfoSystems', 'CIO', 1, '360-287-8610', 'James.Nestor@WP.com');
INSERT INTO Employee(FirstName, LastName, Department, Position, Supervisor, EmailAddress) VALUES('Rick', 'Brown', 'InfoSystems', 'IS2', 12, 'Rick.Brown@WP.com');
INSERT INTO Employee VALUES('Mike', 'Nguyen', 'Research and Development', 'CTO', 1, '360-287-8710', 'Mike.Nguyen@WP.com');
INSERT INTO Employee VALUES('Jason', 'Sleeman', 'Research and Development', 'RD3', 14, '360-287-8720', 'Jason.Sleeman@WP.com');
INSERT INTO Employee VALUES('Mary', 'Smith', 'Production', 'OPS3', 1, '360-287-8810', 'Mary.Smith@WP.com');
INSERT INTO Employee VALUES('Tom', 'Jackson', 'Production', 'OPS2', 14, '360-287-8820', 'Tom.Jackson@WP.com');
INSERT INTO Employee VALUES('George', 'Jones', 'Production', 'OPS2', 15, '360-287-8830', 'George.Jones@WP.com');
INSERT INTO Employee(FirstName, LastName, Department, Position, Supervisor, EmailAddress) VALUES('Julia', 'Hayakawa', 'Production', 'OPS1', 15, 'Julia.Hayakawa@WP.com');
INSERT INTO Employee(FirstName, LastName, Department, Position, Supervisor, EmailAddress) VALUES('Sam', 'Stewart', 'Production', 'OPS1', 15, 'Sam.Stewart@WP.com');
